### ISSUE TITLE
Maybe your code is missing some keys in train.yml

### ISSUE THREAD

**Issue by SysDevHayes** [Hammour-steak/GOUB#7]
Hi @Hammour-steak,

Thank you for your fantastic works!
I have browsing through your code and found some things that you might forgot. 
1. At [L32](https://github.com/Hammour-steak/GOUB/blob/792970f9c0706ee24388855c40e25770d87f56d3/codes/data/LQGT_dataset.py#L32C17-L32C26), you mentioned `if opt["data_type"] == "lmdb":` yet I could not find the key "data_type" being mentioned any where in your train.yml. Perhaps, should this is what it should be?

```
#### datasets
datasets:
  train:
    name: Train_Dataset
    mode: LQGT
    dataroot_GT: ~
    dataroot_LQ: ~
    data_type: img
    use_shuffle: true
    n_workers: 4  # per GPU
    batch_size: 8
    GT_size: 128
    LR_size: 128
    use_flip: true
    use_rot: true
    color: RGB
  val:
    name: Val_Dataset
    mode: LQGT
    dataroot_GT: ~
    dataroot_LQ: ~
```

2. At [L82](https://github.com/Hammour-steak/GOUB/blob/792970f9c0706ee24388855c40e25770d87f56d3/codes/models/base_model.py#L82), you defined the path where the trained models should be exported. Yet I could not find the key `models` being mentioned anywhere in the `train.yml` or `test.yml`. Perhaps, it should be:

```
#### path
path:
  models: /path/to/save/models
  pretrain_model_G: ~
  strict_load: true
  resume_state: ~
```

3. During the inference, you initialize the model at [L21](https://github.com/Hammour-steak/GOUB/blob/792970f9c0706ee24388855c40e25770d87f56d3/codes/tasks/deraining/interface.py#L21). This actually uses [L45](https://github.com/Hammour-steak/GOUB/blob/792970f9c0706ee24388855c40e25770d87f56d3/codes/models/denoising_model.py#L45) to load the model from train.yml at [L56](https://github.com/Hammour-steak/GOUB/blob/792970f9c0706ee24388855c40e25770d87f56d3/codes/tasks/deraining/options/train.yml#L56). From my personal perspective, this is not a practical way to do that. I wonder if we can do it this way:

```
model = create_model(model_params)
model.to(model_params["device"])
pretrained_model_path = "path/to/pretrained_model.pth"
if pretrained_model_path:
    checkpoint = torch.load(pretrained_model_path, map_location=model_params["device"])
    if isinstance(checkpoint, dict) and "state_dict" in checkpoint:
        model.load_state_dict(checkpoint["state_dict"])
    else:
        model.load_state_dict(checkpoint)
    print("Pretrained model loaded successfully.")

sde = util.GOUB(lambda_square=opt["sde"]["lambda_square"], T=opt["sde"]["T"], schedule=opt["sde"]["schedule"], eps=opt["sde"]["eps"], device=device)
sde.set_model(model.model)
```

Thank you so much. Your guidances are priceless!
